name: Update LeetCode Problems

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Runs at 10 PM IST (4:30 PM UTC) on every other Saturday (starting from July 20, 2024)
    - cron: '30 16 */14 * 6'
    # Runs at 10 AM IST (4:30 AM UTC) every Sunday
    - cron: '30 4 * * 0'

jobs:
  update-problems:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      env:
        CLIST_API_KEY: ${{ secrets.CLIST_API_KEY }}
      run: python main.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add README.md docs/leetcode_problems.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "[UPD] Scheduled Job" && git push)
