name: Fetch LeetCode Contest Data

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install playwright
        playwright install
    
    - name: Run data fetching script
      run: python actual.py
    
    - name: Archive contest data
      uses: actions/upload-artifact@v2
      with:
        name: contest-data
        path: contest_data/
